# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: postgres

  task:
    build: .
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./config.yaml:/config_file.yaml
      - ./vehicles.csv:/vehicles.csv
